### PR TITLE
Added initial ESLint and Flow support

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by amoghbanta** [comment]
Hi @amilajack, it is tough to review these many file changes. Could you please change the indentation back to as it was ( indent_size =4 from indent_size = 2) and then send the PR.
Thanks.

**Comment by amilajack** [comment]
Fixed the indentation 🎉

**Comment by ankitpopli1891** [comment]
Hey @amilajack, thanks for all the effort. It's much appreciated. I just have a small suggestion if you don't mind. 

This pull request has grown a lot in size and it will be difficult for us to go through **13K** LOC changes, most of which should be ignored (like indentation & other code style issues). It would be better if you could just send a different PR with only the **flow-eslint-support** related changes.

Sounds cool ?

**Comment by amilajack** [comment]
Most of the LOC changes are autogenerated type definitions and the yarn.lock. If you ignore those, reviewing should be much easier

**Comment by kkszysiu** [comment]
Wouldn't be better to use ident of 4 spaces everywhere? :)

Anyway, thanks!

**Comment by piranna** [comment]
Is the `flow-typed` folder needed? Can't it be autogenerated? This way the pull-request would be fairly smaller...

**Comment by amoghbanta** [comment]
Closing this one as this PR would no longer be valid with the template.

**Pull request closed without merging**
